version: '3.4'

services:
    sqlserver2019:
        container_name: dev_mssql2022
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - MSSQL_SA_PASSWORD=Hst@9asc
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"
        volumes: 
          - mssql_data:/var/opt/mssql/
    
volumes:
    mssql_data:
        driver: local