version: '3.5'
services:
    redis-server:
        container_name: redis-contaner
        image: redis:latest
        ports:
            - 16379:6379
        volumes:
            - redis:/etc/redis/redis.conf
            - redis_data:/data
        command: ["redis-server", "/etc/redis/redis.conf"]
        restart: always
      
volumes:
    redis:
    redis_data:
