version: '3.5'
services:
    cache:
        container_name: dev-redis
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data
        restart: always
        
    redisinsight:
        container_name: dev-redisinsight
        image: redislabs/redisinsight:latest
        ports:
            - 5540:5540
        restart: always

volumes:
    redis_data: