version: '3.2'
services:
    rabbitmq:
        container_name: dev_rabbitmq
        image: rabbitmq:management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
        restart: always     
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge